$(document).ready(function(){
    $('.navbar-toggler').click(function(){
        $(".navbar-nav").toggleClass('nav-col');
    });
    $(".header1").click(function(){
        $(".body1").toggle(100);
    });
    $(".header2").click(function(){
        $(".body2").toggle(100);
    });
    $(".header3").click(function(){
        $(".body3").toggle(100);
    });
});